import type { Metadata } from 'next'
import Script from 'next/script'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

const GoogleAnalytics = ({ ga_id }: { ga_id: string }) => (
	<>
		<Script
			async
			src={`https://www.googletagmanager.com/gtag/js? 
      id=${ga_id}`}
		></Script>
		<Script
			id='google-analytics'
			dangerouslySetInnerHTML={{
				__html: `
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', '${ga_id}');
        `,
			}}
		></Script>
	</>
)

export const metadata: Metadata = {
	title: 'Підписка на шкарпетки',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html className='scroll-smooth' lang='ua'>
			<head>
				<Script id='google-tag-manager'>
					{`
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-KN293MZD');
            `}
				</Script>
			</head>
			<body className={inter.className}>
				{process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS ? (
					<GoogleAnalytics ga_id={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS} />
				) : null}
				{children}
				<Header />
			</body>
		</html>
	)
}
