import type { Metadata } from 'next'
import Script from 'next/script'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const GoogleAnalytics = ({ ga_id }: { ga_id: string }) => (
	<>
		<Script
			async
			src={`https://www.googletagmanager.com/gtag/js? 
      id=${ga_id}`}
		></Script>
		<Script
			id='google-analytics'
			dangerouslySetInnerHTML={{
				__html: `
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', '${ga_id}');
        `,
			}}
		></Script>
	</>
)

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html className='scroll-smooth' lang='ua'>
			<body className={inter.className}>
				{process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS ? (
					<GoogleAnalytics ga_id={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS} />
				) : null}
				{children}
			</body>
		</html>
	)
}
